name: Deploy Next.js to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t your_dockerhub_username/your_nextjs_app:latest .

      - name: Push Docker image to DockerHub
        run: docker push your_dockerhub_username/your_nextjs_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean Droplet via SSH (using password)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /home/ubuntu/bazigaar-website
            docker-compose pull
            docker-compose up -d --build
